 ---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизироваться используя аккаунт Github
  - Пользователь должен иметь возможность авторизироваться используя аккаунт Discord
  - Пользователь должен иметь возможность авторизироваться используя ранее созданный аккаунт
  - Пользователь должен иметь возможность запустить пробную игру без авторизации
  - Пользователь должен иметь возможность создать игру с другим случайным пользователем
  - Пользователь должен иметь возможность создать игру с ботом
  - Пользователь должен иметь возможность создать игру с выбранным оппонентом (другом)
  - В режиме игры каждый пользователь должен видеть код своего соперника в режиме онлайн
  - Оба игрока видят два редактора: слева - свой редактор, справа - соперника.
  - Каждый игрок имеет кнопку "отладки" для проверки своего решения. Попыток проверки неограниченно.
  - На сайте должна быть возможность просмотра таблицы рейтинга игроков с фильтрацией 
  - В личном кабинете пользователя должна быть доступна статистика по общему количеству игр, количеству побед, используемым ЯП
  - Пользователь должен иметь возможность создания турнира 

non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Пользователи должны иметь статус "в сети", "не в сети"
  - Рядом с аватаром должен отображаться рейтинг пользователя
  - Боты должны быть отмечены пиктограммой бота
